- name: Create nginx docker container
  hosts: localhost
  connection: local
  tasks:
    - name: nginx container:
      community.docker.docker_container:
        image: docker.io/nginx
        state: started
        ports:
          - "8080:80"