- name: Retrive hashi vault secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Get secret KV
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=demo/data/ssh:azuser token={{ token }}, url=http://vault.nareshdevops1218.online:8201') }}"
      