- name: Retrive hashi vault secrets
  hosts: localhost
  connection: local
  tasks:
    name: Get secret KV
    ansible.builtin.debug::
    response: "{{ lookup('community.hashi_vault.vault_kv2_get', 'demo', url='http://vault.nareshdevops1218.online:8201') }}"